version: '2'
services:
    javaapp-app:
        image: javaapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://javaapp-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=javaApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    javaapp-mongodb:
        extends:
            file: mongodb.yml
            service: javaapp-mongodb
